# @package _global_
defaults:
  - _self_
  - model: logistic_regression
  - data: stress_data
  - training: default
  - search_space: logistic_regression
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

project_name: uq-stress-det
seed: 42
optimized_metric: "f1_score"

best_params: /home/x271828/projects/UQ-stress-det/multirun/xgboost/2026-08-19_23-53-45/optimization_results.yaml

# Optuna-specific settings
hydra:
  # Mode: MULTIRUN for Optuna tuning, RUN for final evaluation
  mode: MULTIRUN
  # Evaluation Output (Used when hydra.mode=RUN)
  run:
    dir: outputs/${model.model_name}/${now:%Y-%m-%d_%H-%M-%S}/eval_seed_${seed}_stratified_split_${data.stratified_split}_calibration_${data.calibrate}
  sweep:
    dir: multirun/${model.model_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: trial_${hydra.job.num}_seed_${seed}_stratified_split_${data.stratified_split}
  sweeper:
    sampler:
      seed: ${seed}
      n_startup_trials: 5
      n_ei_candidates: 24
    direction: maximize
    study_name: ${model.model_name}_tuning
    storage: null
    n_trials: 50
    # n_trials: 2
    n_jobs: 1

wandb:
  project: "stress-detection"
  run_name: ${model.model_name}_optuna
  entity: null
